- name: 'MJML View'
  uriPattern: '{node}.mjml'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'html'
    'mjml': true
  appendExceedingArguments: true
  httpMethods: ['GET']
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
