Garagist:
  Mjml:
    apiEndpoint: '%env:MJML_API_ENDPOINT%'

    # Output the node type name of an content element who has no dedicated rendering
    # Can be true, false or 'comment'
    debugOutputMode: true

    theme:
      defaults:
        color: '#000'
        font-size: 14px
        line-height: 1.5
        font-family: 'Ubuntu, Helvetica, Arial, sans-serif;'
      colors: []
      fontSize: []
  Mautic:
    routeArgument:
      htmlTemplate: mjml
      plaintextTemplate: plaintext
