Garagist:
  Mjml:
    # If set to 'true', the API from mjml.io will be used to render the email
    # If you want to use the API from mjml.io, you will need to register at https://mjml.io/, get an API key, set the applicationID and the secretKey
    apiEndpoint: '%env:MJML_API_ENDPOINT%'
    applicationID: '%env:MJML_API_APPLICATION_ID%'
    secretKey: '%env:MJML_API_SECRET_KEY%'

    # Output the node type name of an content element who has no dedicated rendering
    # Can be true, false or 'comment'
    debugOutputMode: true

    # Set the tracking pixel for the email
    # If you use Garagist.Mautic, there is no need to set this, as it will be set automatically
    trackingPixel: false

    theme:
      defaults:
        color: '#000'
        font-size: 14px
        line-height: 1.5
        font-family: 'Ubuntu, Helvetica, Arial, sans-serif;'
      colors:
        white: '#ffffff'
        black: '#000000'
        transparent: 'transparent'
        gray:
          50: '#f9fafb'
          100: '#f3f4f6'
          200: '#e5e7eb'
          300: '#d1d5db'
          400: '#9ca3af'
          500: '#6b7280'
          600: '#4b5563'
          700: '#374151'
          800: '#1f2937'
          900: '#111827'
      font-size:
        xs:
          pixel: 12
          lineHeight: 16px
        sm:
          pixel: 14
          lineHeight: 20px
        base:
          pixel: 16
          lineHeight: 24px
        lg:
          pixel: 18
          lineHeight: 28px
        xl:
          pixel: 20
          lineHeight: 28px
        2xl:
          pixel: 24
          lineHeight: 32px
        3xl:
          pixel: 30
          lineHeight: 36px
        4xl:
          pixel: 36
          lineHeight: 40px
        5xl:
          pixel: 48
          lineHeight: 1
        6xl:
          pixel: 60
          lineHeight: 1
        7xl:
          pixel: 72
          lineHeight: 1
        8xl:
          pixel: 96
          lineHeight: 1
        9xl:
          pixel: 128
          lineHeight: 1
      fontWeight:
        thin: 100
        extralight: 200
        light: 300
        normal: 400
        medium: 500
        semibold: 600
        bold: 700
        extrabold: 800
        black: 900
  Mautic:
    routeArgument:
      htmlTemplate: mjml
      plaintextTemplate: plaintext
